version: '3.4'

services:
      store:
        image: ${DOCKER_REGISTRY-}store
        build:
          context: .
          dockerfile: Store/Dockerfile
        ports:
            - "8081:80"
        depends_on:
            - db

      db:
        image: "mcr.microsoft.com/mssql/server"
        ports:
          - "1433:1433"
        environment:
            SA_PASSWORD: "p@ssw0rd!"
            ACCEPT_EULA: "Y"
        healthcheck:
            test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "p@ssw0rd!", "-Q", "select 1" ]
            interval: 10s
            timeout: 5s
            retries: 5
